### ISSUE TITLE
Hyperlink Removes Formatting

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#348] opened 2020-04-14 15:20 UTC
**Describe the bug**
A user loses formatting in hyperlink

**To Reproduce**
1. Go to the [live demo](https://accordproject-markdown-editor.netlify.com/)
2. Select everything with <kbd>MOD</kbd> + <kbd>A</kbd>
3. Select hyperlink button
4. Enter a hyperlink and apply
5. Formatting breaks

**Expected behavior**
Formatting should persist, or maybe protections on link size?

**Comment by DianaLease** [comment] 2020-04-14 19:14
Closing as a dupe of #330

**Closed by DianaLease** 2020-04-14 19:14 UTC
Labels: Slate57
