### ISSUE TITLE
Incorrect alignment of Bold Icon

### ISSUE THREAD

**Issue by arteevraina** [accordproject/markdown-editor#361] opened 2020-04-17 18:21 UTC
## Screenshot
![image](https://user-images.githubusercontent.com/43968121/79600867-79698700-8105-11ea-803b-a10d7316079d.png)

It should display Bold Icon without covering its ends.

**Comment by irmerk** [comment] 2020-04-17 19:52
What width are you at? In the `markdown-editor` and `cicero-ui` demos I don't see this issue.

**Comment by arteevraina** [comment] 2020-04-17 21:35
@irmerk I was using the demo[https://cicero-ui.netlify.app/?path=/story/components-template-library--template-library] with a `screen-zoom of 100%.`.
I was displaying properly in `cicero-ui`.

**Comment by nik72619c** [comment] 2020-04-17 22:27
Not able to 

> What width are you at? In the `markdown-editor` and `cicero-ui` demos I don't see this issue.

Same, unable to reproduce it
<img width="1280" alt="Screenshot 2020-04-18 at 3 56 13 AM" src="https://user-images.githubusercontent.com/30630904/79618783-a5e2ca80-8128-11ea-9f52-1a60db5a2093.png">

**Comment by arteevraina** [comment] 2020-04-18 18:11
@nik72619c Sorry! I shared the link of cicero-ui. I have updated the link you can check if you can reproduce it in `mardown-editor`

**Comment by nik72619c** [comment] 2020-04-18 19:09
Thanks @arteevraina!
Still not able to reproduce though :(

<img width="1280" alt="Screenshot 2020-04-19 at 12 30 45 AM" src="https://user-images.githubusercontent.com/30630904/79668819-1ba47000-81d5-11ea-9e56-f9e9d327080d.png">

**Comment by irmerk** [comment] 2020-04-20 13:08
Closing, @arteevraina reopen or make a new issue if you have steps to reproduce.

**Closed by irmerk** 2020-04-20 13:08 UTC
