### ISSUE TITLE
Markdown support: Nested lists

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-editor#191] opened 2019-11-12 23:55 UTC
**Is your feature request related to a problem? Please describe.**
Markdown documents often include lists, and sometimes nested lists.

It would be nice if the editor allowed creating/editing/deleting nested lists.

**Describe the solution you'd like**
The ability to create and edit a nested lists.

It would be nice to have a convenient way to switch between nesting levels.

**Describe alternatives you've considered**

**Additional context**

**Comment by DianaLease** [comment] 2020-01-07 16:19
closing because duplicate of https://github.com/accordproject/markdown-editor/issues/195

**Closed by DianaLease** 2020-01-07 16:19 UTC
Labels: Difficulty: Medium
