### ISSUE TITLE
Copy hyperlink in modal doesn't work

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#369] opened 2020-04-21 06:20 UTC
Pressing the "Copy hyperlink text" button in the link editor modal doesn't copy the text to the clipboard.

**To Reproduce**
1. Go to https://cicero-ui.netlify.app/?path=/story/components-contract-editor--contract-editor
2. Add a hyperlink, using the toolbar and set the URL
3. Reopen the dialog and press the "copy hyperlink text" button
4. Paste the link
5. The link was not copied to the keyboard

**Expected behavior**
Hyperlink should be copied.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari
 - Version 13.1

**Comment by nik72619c** [comment] 2020-04-21 06:21
@dselman would like to work on this one :)

**Comment by dselman** [comment] 2020-04-21 06:22
It's yours!

**Comment by elit-altum** [comment] 2020-04-24 15:04
@nik72619c are you able to recreate the issue ?

**Comment by irmerk** [comment] 2020-04-24 15:22
Yeah I'm unable to reproduce this. Closing, let me know if you can recreate it.

**Closed by irmerk** 2020-04-24 15:22 UTC
Labels: Slate57, Type: Bug 🐛

**Comment by nik72619c** [comment] 2020-04-24 21:02
not able to reproduce it either @elit-altum @irmerk
