### ISSUE TITLE
Multi-line Codeblocks Overlap in Blockquotes

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#354] opened 2020-04-16 09:11 UTC
**Describe the bug**
Multiple codeblock lines overlap each other when put in blockquotes.

**To Reproduce**
1. Go to [the demo.](https://accordproject-markdown-editor.netlify.app/)
2. Select multiple lines of text 
3. Click on the `Quote` button from the `Toolbar Menu`
4. Click on the `Code` button from the `Toolbar Menu`

**Expected behavior**
The `line-height` of blockquotes should increased so the codeblocks don't overlap.

**Screenshots**
![codeblock](https://user-images.githubusercontent.com/47667325/79437698-2fdb4800-7ff0-11ea-8d58-b3240ed287ae.PNG)

**Additional context**
I'd like to work on this!

**Comment by irmerk** [comment] 2020-04-23 14:16
Cannot reproduce, closing.

**Closed by irmerk** 2020-04-23 14:16 UTC
Labels: Slate57

**Comment by shrey-sachdeva2000** [comment] 2020-04-23 14:47
> Cannot reproduce, closing.

Yup, now sure what changed but it's fixed now!
